spring:
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: licensing-service
            client-secret: UAKOomxRC7c0SD96YeA5jGNxmY6m4Egg
            authorization-grant-type: client_credentials
            scope: openid
        provider:
          keycloak:
            token-uri: http://localhost:8080/realms/spmia-realm/protocol/openid-connect/token
            user-info-uri: http://localhost:8080/realms/spmia-realm/protocol/openid-connect/userinfo
